### ISSUE TITLE
use raf module instead of requestAnimationFrame

### ISSUE THREAD

**Issue by yocontra** [common-tater/volume-meter#2]
will help this work across browsers + also work in a server environment

**Comment by jessetane** [comment]
requestAnimationFrame has pretty good support by now - the bigger issue is probably web audio. if we switched to the raf shim, where would this work that it didn't before?

also, I'm curious, how would you use something like this on a server?

**Comment by yocontra** [comment]
Don't have any specific examples, I just think its cool when a standalone module doesn't rely on or assume any globals existing. I've had a ton of problems before (especially with WebRTC) where modules make a ton of assumptions about the environment and end up excluding whole platforms.

**Comment by jessetane** [comment]
totally get it and agree in principle, just wanted to save bytes since I figured this was definitely browser only. if you want to send a pr tho i will merge it.
